services:
  bind9:
    container_name: bind9
    image: ubuntu/bind9:latest
    environment:
      - TZ=Asia/Yekaterinburg
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - '/bind/named.conf:/etc/bind/named.conf'
      - '/bind/cache/bind:/var/cache/bind'
      - '/bind/lib/bind:/var/lib/bind'
      - '/bind/db.tsuran.local:/etc/bind/db.tsuran.local'
    restart: always


